server:
  port: 8182
  servlet:
    context-path: /tech-bazzar-cart

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url.defaultZone: http://eureka-service:8761/eureka

integrations:
  product-service:
    url: http://core-service:8183/tech-bazzar-core/
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000

cart-service:
  cart-prefix: tech_cart_