server:
  port: 8183
  servlet:
    context-path: /tech-bazzar-core

spring:
  servlet:
    multipart:
      max-file-size: 5MB

  datasource:
    url: ${url_db_core}
    driver-class-name: org.postgresql.Driver
    username: ${db_username}
    password: ${db_password}

  flyway:
    baselineOnMigrate: true
    url: ${url_db_core}
    user: ${db_username}
    password: ${db_password}
    validateOnMigrate: false

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update
  http:
    encoding:
      charset: UTF-8
      force: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

integrations:
  auth-service:
    url: http://localhost:8181/tech-bazzar-user/
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000

  cart-service:
    url: http://localhost:8182/tech-bazzar-cart/
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000

  organization-service:
    url: http://localhost:8185/tech-bazzar-organization/
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000

  picture-service:
    url: http://localhost:8555/tech-bazzar-picture/
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000