server:
  port: 8184
  servlet:
    context-path: /tech-bazzar-notification

spring:
#  flyway:
#    baselineOnMigrate: true
#    url: ${url_db_notification}
#    user: ${db_username}
#    password: ${db_password}
#    validateOnMigrate: false

  datasource:
    url: jdbc:postgresql://postgres-notification-service:5432/notification_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin

  jpa:
    showSql: true
    databasePlatform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddlAuto: update

  mail:
    protocol: smtps
    host: smtp.mail.ru
    port: 465
    username: bazzar@mail.ru
    password: 029347902374

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka