server:
  port: 8185
  servlet:
    context-path: /tech-bazzar-organization

spring:
  datasource:
    url: ${url_db_organization}
    driver-class-name: org.postgresql.Driver
    username: ${db_username}
    password: ${db_password}

  flyway:
    baselineOnMigrate: true
    url: ${url_db_organization}
    user: ${db_username}
    password: ${db_password}
    validateOnMigrate: false

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  swagger-ui:
    supported-submit-methods: "get"
