server:
  port: 8181
  servlet:
    context-path: /tech-bazzar-user

spring:
#  flyway:
#    baselineOnMigrate: true
#    url: ${url_db_user}
#    user: ${db_username}
#    password: ${db_password}
#    validateOnMigrate: false

  datasource:
    url: jdbc:postgresql://postgres-user-service:5432/user_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin

  jpa:
    showSql: true
    databasePlatform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddlAuto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka

integrations:
  notification-service:
    url: http://notification-service:8184/tech-bazzar-notification/
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000