server:
  port: 8181
  servlet:
    context-path: /tech-bazzar-user

spring:
  flyway:
    baselineOnMigrate: true
    url: ${url_db_user}
    user: ${db_username}
    password: ${db_password}
    validateOnMigrate: false

  datasource:
    url: ${url_db_user}
    driverClassName: org.postgresql.Driver
    username: ${db_username}
    password: ${db_password}

  jpa:
    showSql: true
    databasePlatform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddlAuto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

integrations:
  notification-service:
    url: http://localhost:8184/tech-bazzar-notification/
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000